MODEL:
    G_ARCHITECTURE: "GOOD"
    D_ARCHITECTURE: "GOOD"
    G_PRETRAINED_MODEL_PATH: './output/coco_64_step_1_1/models/G_9999.ckpt'
    D_PRETRAINED_MODEL_PATH: './output/coco_64_step_1_1/models/D_9999.ckpt'

DATA:
    USE_DATASET: "coco"  # "cifar10", "nuswide81", "coco"
    LABEL_DIM: 80  # 80个类别
    DB_SIZE: 117218  # 检索集大小：122218-5000
    TEST_SIZE: 5000  # 查询集大小：5000
    WIDTH_HEIGHT: 64
    MAP_R: 117218 
    LIST_ROOT: "./data/coco"
    DATA_ROOT: "./data/coco"
    OUTPUT_DIR: "./output/coco_64_step_1_2"

TRAIN:
    BATCH_SIZE: 64
    ITERS: 10000   # 迭代1万次
    CROSS_ENTROPY_ALPHA: 10
    LR: 1e-4  # Initial learning rate
    G_LR: 1e-4  # 1e-4
    DECAY: True  # Whether to decay LR over learning
    N_CRITIC: 5 # Critic steps per generator steps
    EVAL_FREQUENCY: 1000  # How frequently to evaluate and save model
    CHECKPOINT_FREQUENCY: 1000
    ACGAN_SCALE: 1.0
    ACGAN_SCALE_G: 10.0
    WGAN_SCALE: 1.0  
    WGAN_SCALE_G: 1.0
