MODEL:
    G_ARCHITECTURE: "GOOD"
    D_ARCHITECTURE: "ALEXNET"
    G_PRETRAINED_MODEL_PATH: "./output/flickr25k_64_step_1_1/models/G_8999.ckpt"
    D_PRETRAINED_MODEL_PATH: "./output/flickr25k_64_finetune_1/models/D_3999.ckpt"

DATA:
    USE_DATASET: "flickr25k"  # "cifar10", "nuswide81", "coco"
    LABEL_DIM: 24
    DB_SIZE: 23000
    TEST_SIZE: 5000
    WIDTH_HEIGHT: 64
    MAP_R: 23000  
    LIST_ROOT: "./data/flickr25k"
    DATA_ROOT: "./data/flickr25k"
    OUTPUT_DIR: "./output/flickr25k_64_evaluation_1"

TRAIN:
    EVALUATE_MODE: True
    BATCH_SIZE: 128
    ITERS: 10000
    CROSS_ENTROPY_ALPHA: 10
    LR: 1e-4  # Initial learning rate
    G_LR: 0.0  # 1e-4
    DECAY: True  # Whether to decay LR over learning
    N_CRITIC: 1  # Critic steps per generator steps
    EVAL_FREQUENCY: 1
    SAMPLE_FREQUENCY: 1
    ACGAN_SCALE: 1.0
    ACGAN_SCALE_FAKE: 0.0 # 1.0
    WGAN_SCALE: 0.0  
    WGAN_SCALE_GP: 10.0
    ACGAN_SCALE_G: 0.1
    WGAN_SCALE_G: 1.0
