MODEL:
    G_ARCHITECTURE: "NORM"
    D_ARCHITECTURE: "ALEXNET"
    G_PRETRAINED_MODEL_PATH: "./output/nuswide-10_32_step_1_5/models/G_45999.ckpt"
    D_PRETRAINED_MODEL_PATH: "./output/nuswide-10_32_finetune_5/models/D_3999.ckpt"

DATA:
    USE_DATASET: "nuswide-10"  # "cifar10", "nuswide81", "coco"
    LABEL_DIM: 10
    DB_SIZE: 181577 
    TEST_SIZE: 10500 
    WIDTH_HEIGHT: 32 
    MAP_R: 181577
    LIST_ROOT: "./data/nuswide-10"
    DATA_ROOT: "./data/nuswide-10"
    OUTPUT_DIR: "./output/nuswide-10_32_evaluation_5"

TRAIN:
    EVALUATE_MODE: True
    BATCH_SIZE: 128
    ITERS: 10000
    CROSS_ENTROPY_ALPHA: 10
    LR: 1e-4  # Initial learning rate
    G_LR: 0.0  # 1e-4
    DECAY: True  # Whether to decay LR over learning
    N_CRITIC: 1  # Critic steps per generator steps
    EVAL_FREQUENCY: 1
    SAMPLE_FREQUENCY: 1
    ACGAN_SCALE: 1.0
    ACGAN_SCALE_FAKE: 0.0 # 1.0
    WGAN_SCALE: 0.0  
    WGAN_SCALE_GP: 10.0
    ACGAN_SCALE_G: 0.1
    WGAN_SCALE_G: 1.0
